app/controllers/CooperationController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\modules\pages\api\Page;

class CooperationController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionDealership()
    {
        $page = Page::get('page-dealership');

        return $this->render('dealership', [
            'page' => $page
        ]);
    }

    public function actionCorporateClient()
    {
        $page = Page::get('page-corporate-client');

        return $this->render('corporate-client', [
            'page' => $page
        ]);
    }
}

app/views/cooperation/_advantages-corporate.php
<div class="advantages advantages_cooperation">
	<div class="advantages__list">
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/cart.png" alt=""></div>
				<div class="advantages__title">Широкий ассортимент <br>продукции высокого качества</div>
			</div>
			
		</div>

		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/instrument.png" alt=""></div>
				<div class="advantages__title">Производство и монтаж <br>конструкций любой сложности</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/skidki.png" alt=""></div>
				<div class="advantages__title">Гибкая система скидок <br>и индивидуальные ценовые предложения</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/support.png" alt=""></div>
				<div class="advantages__title">Строгое соблюдение сроков изготовления изделий <br>и выполнения работ</div>
			</div>
		</div>
	</div>
</div>

app/views/cooperation/_advantages-dealership.php
<div class="advantages advantages_cooperation">
	<div class="advantages__list">
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/cart.png" alt=""></div>
				<div class="advantages__title">Широкий ассортимент <br>выпускаемой продукции</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/people.png" alt=""></div>
				<div class="advantages__title">Индивидуальный подход <br>к каждому дилеру</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/instrument.png" alt=""></div>
				<div class="advantages__title">Все необходимые комплектующие <br>для проведения монтажных работ</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/skidki.png" alt=""></div>
				<div class="advantages__title">Гибкую систему скидок <br>для новичков и постоянных клиентов</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/phone.png" alt=""></div>
				<div class="advantages__title">Предварительный просчет <br>стоимости заказа по телефону</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/payment.png" alt=""></div>
				<div class="advantages__title">Специальные условия <br>оплаты</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/delivery.png" alt=""></div>
				<div class="advantages__title">Квалифицированную доставку <br>готовых конструкций <br>и комплектующих для монтажа</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/support.png" alt=""></div>
				<div class="advantages__title">Информационную <br>и техническую поддержку <br>клиентов в режиме on-line</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/eye.png" alt=""></div>
				<div class="advantages__title">Бесплатные образцы <br>продукции, выполненные <br>по заказу клиента</div>
			</div>
			
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/docs.png" alt=""></div>
				<div class="advantages__title">Полный пакет документов</div>
			</div>
			
		</div>
	</div>
</div>

app/views/cooperation/_cooperation-form.php
<section class="section section_gray section_corporation-form">
	<div class="section__inner">
		<div class="container">
			<div class="section__title">Надеемся в Вашем лице приобрести <span class="section__title_blue">надежного партнера.</span><br>Будем рады <span class="section__title_blue">сотрудничеству</span> с вами!</div>
			<form action="" class="get-stock__form js__form">
				<div class="get-stock__row">
					<div class="get-stock__input">
						<div class="input">
							<div class="input__wrapper">
								<input type="text" class="input__input" placeholder="Ваше имя" data-type="name" name="name">
							</div>
						</div>
					</div>
					<div class="get-stock__input">
						<div class="input">
							<div class="input__wrapper">
								<input type="text" class="input__input" placeholder="Ваш телефон" data-type="phone" name="phone">
							</div>
						</div>
					</div>
				</div>
				<div class="get-stock__row">
					<div class="get-stock__textarea">
						<div class="textarea">
							<div class="textarea__wrapper">
								<textarea name="message" id="" placeholder="Сообщение" class="textarea__textarea" data-type="requared"></textarea>
							</div>
						</div>
					</div>
				</div>
				<div class="get-stock__row">
					<div class="get-stock__checkbox">
						<label class="checkbox">
							<input type="checkbox" class="checkbox__input" data-type="checkbox">
							<div class="checkbox__icon"></div>
							Я ознакомился и согласен с&nbsp;<span data-popup-open="agreement">правилами</span>
						</label>
					</div>
					<div class="get-stock__btn">
						<button class="btn">Отправить</button>
					</div>
				</div>
				<div class="response"></div>
			</form>
		</div>
	</div>
</section>

app/views/cooperation/_cooperation-menu.php
<?php
use yii\widgets\Menu;
?>

<nav class="tags-menu">
	<?= Menu::widget([
		'options' => [
			'class' => 'tags-menu__list',
		],
		'items' => [
			['label' => 'Дилерство', 'url' => ['/cooperation/dealership']],
			['label' => 'Корпоративным клиентам', 'url' => ['/cooperation/corporate-client']]
		],
		'itemOptions'=>['class'=>'tags-menu__item'],
		'activeCssClass'=>'is-active',
	]); ?>
</nav>

app/views/cooperation/corporate-client.php
<?php
	use app\modules\pages\api\Page;
	use yii\widgets\Breadcrumbs;

	$this->title = $page->seo('title', $page->model->title);
	$this->registerMetaTag(
		['name' => 'description',
		'content' => $page->seo('description', $page->model->title)
	]);

	$this->params['breadcrumbs'][] = ['label' => $page->title];
?>

<div class="breadcrumb__wrapper">
	<div class="container">
		<?= Breadcrumbs::widget([
			'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
		])?>
	</div>
</div>

<section class="section">
	<div class="section__inner">
		<div class="container">
			<h1 class="section__title"><?= Page::title($page->seo('h1', $page->title)); ?></h1>

			<?= $this->render('_cooperation-menu', []);?>

			<div class="section__text section__text_left">
				<?=$page->text;?>
			</div>

			<div class="section__text section__text_left">
				<?=$page->text_2;?>
			</div>

			<?= $this->render('_advantages-corporate', []);?>
		</div>
	</div>
</section>

<?= $this->render('_cooperation-form', []);?>

app/views/cooperation/dealership.php
<?php
	use app\modules\pages\api\Page;
	use yii\widgets\Breadcrumbs;

	$this->title = $page->seo('title', $page->model->title);
	$this->registerMetaTag(
		['name' => 'description',
		'content' => $page->seo('description', $page->model->title)
	]);

	$this->params['breadcrumbs'][] = ['label' => $page->title];
?>

<div class="breadcrumb__wrapper">
	<div class="container">
		<?= Breadcrumbs::widget([
			'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
		])?>
	</div>
</div>

<section class="section">
	<div class="section__inner">
		<div class="container">
			<h1 class="section__title"><?= Page::title($page->seo('h1', $page->title)); ?></h1>

			<?= $this->render('_cooperation-menu', []);?>

			<div class="section__subtitle">
				<?=$page->text;?>
			</div>

			<div class="section__text section__text_left">
				<?=$page->text_2;?>
			</div>
			
			<?= $this->render('_advantages-dealership', []);?>
		</div>
	</div>
	
</section>

<?= $this->render('_cooperation-form', []);?>