app/controllers/ProductionController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\modules\productions\api\Catalog;
use app\modules\pages\api\Page;
use app\modules\works\api\Gallery;
use app\modules\certificate\api\Certificate;
use app\modules\reviews\api\News as Reviews;

class ProductionController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    private function getCategoryList ()
    {
        $catalogCategories = Catalog::cats();

        return array_filter($catalogCategories, function ($item, $index) {
            return ($item->depth === '0');
        }, ARRAY_FILTER_USE_BOTH);
    }

    private function getWorks ($cat)
    {   
        $category = Gallery::cat($cat);

        if ($category) {
            return $category->photos();
        } else {
            return [];
        }
    }

    public function actionIndex()
    {
        $page = Page::get('page-catalog');
        $categoryList = $this->getCategoryList();
        // $cats = Catalog::cats();
        // return $this->redirect('/production/' . current($cats)->slug);
        return $this->render('index', [
            'page' => $page,
            'categoryList' => $categoryList
        ]);
    }

    public function actionCategory($cat, $sub = null)
    {
        $parent = null;
        $curretCat = $cat;
        if ($sub) {
            $curretCat = $sub;
            $parent = Catalog::cat($cat);
        }
        $category = Catalog::cat($curretCat);
        $categories = Catalog::tree();
        $categoryMenu = Catalog::menu($categories, 'catalog', $cat);
        $subCategoriesTemp = Catalog::children($cat);

        $works = $this->getWorks($curretCat);
        $certificates = Certificate::cat('certificate');
        $reviews = Reviews::items(['pagination' => ['pageSize' => 10]]);
        $subCategories = [];


        foreach ($reviews as $key => $value) {
            if ($value->model->video) {
                unset($reviews[$key]);
            }
        }

        foreach ($subCategoriesTemp as $key => $item) {

            if ($item->slug !== $curretCat) {
                $subCategories[] = $item;
            }
        }

        $subMenu = Catalog::menu($subCategories, 'subcatalog', $cat, Catalog::cat($cat));
        // var_dump($reviews); exit;

        Reviews::plugin();
        Gallery::plugin();

        return $this->render('category', [
            'categoryMenu' => $categoryMenu,
            'category' => $category,
            'categoryId' => $sub ?: $cat,
            'subCategories' => $subCategories,
            'parent' => $parent,
            'subMenu' => $subMenu,
            'items' => $category->items(['pagination' => ['pageSize' => 9]]),
            'works' => $works,
            'reviews' => array_slice($reviews, 0, 2),
            'certificates' => $certificates->photos(['pagination' => ['pageSize' => 6]]),
        ]);
    }
}

app/controllers/ServicesController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\modules\pages\api\Page;
use app\modules\services\api\Services;

class ServicesController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $page = Page::get('page-services');
        $services = Services::items();

        return $this->render('index', [
            'page' => $page,
            'services' => $services
        ]);
    }

    public function actionView($slug)
    {
        $item = Services::get($slug);

        return $this->render('view', [
            'item' => $item
        ]);
    }
}

app/controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\modules\pages\api\Page;
use app\modules\topslider\api\Carousel;
use app\modules\productions\api\Catalog;
use app\modules\services\api\Services;
use app\modules\works\api\Gallery;
use app\modules\reviews\api\News as Reviews;

class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    private function getCategoryList ()
    {
        $catalogCategories = Catalog::cats();

        return array_filter($catalogCategories, function ($item, $index) {
            return ($item->depth === '0');
        }, ARRAY_FILTER_USE_BOTH);
    }

    public function actionIndex()
    {
        $page = Page::get('page-index');
        $categoryList = $this->getCategoryList();
        $slides = Carousel::items();
        $services = Services::items();
        $reviews = Reviews::items([
            'pagination' => ['pageSize' => 999]
        ]);

//        $reviews = array_filter($reviews, function ($item) {
//            return $item->model['video'];
//        });


        $categories = Gallery::tree();

        $categoryWorks = [];

        foreach ($categories as $key => $value) {

            $category = Gallery::cat($value->slug);

            $categoryWorks[] = [
                'label' => $value->title,
                'url' => $value->slug,
                'items' => $category->photos()
            ];
        }

        Gallery::plugin();

        return $this->render('index', [
            'page' => $page,
            'categoryList' => $categoryList,
            'slides' => $slides,
            'services' => $services,
            'reviews' => $reviews,
            'works' => Gallery::last(10),
            'categoryWorks' => $categoryWorks
        ]);
    }
}

app/views/site/_advantages.php
<div class="advantages">
	<div class="advantages__list">
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/proizvodstvo.png" alt=""></div>
				<div class="advantages__title">Свой производственный <br>комплекс с системой ОТК</div>
			</div>
			<div class="advantages__body">
				<div class="advantages__text">Производим изделия из пвх и алюминия любой сложности, том числе нестандартных конфигураций. Каждый этап производства проходит под контролем собственной службы качества. Сотрудничаем только с поставщиками, проверенными временем.</div>
			</div>
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/garantiya.png" alt=""></div>
				<div class="advantages__title">Письменная гарантия <br>качества 10 лет</div>
			</div>
			<div class="advantages__body">
				<div class="advantages__text">Мы несем ответственность за качество продукции (гарантия предоставляется на изделия из ПВХ с монтажом)</div>
			</div>
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/innovacii.png" alt=""></div>
				<div class="advantages__title">Инновации для Вашего <br>удобства</div>
			</div>
			<div class="advantages__body">
				<div class="advantages__text">Использование технологии  теплого края для производства стеклопакетов. Вся продукция, выпускаемая на нашем предприятии, соответствует нормам ГОСТа.</div>
			</div>
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/skidki.png" alt=""></div>
				<div class="advantages__title">Гибкая система <br>скидок</div>
			</div>
			<div class="advantages__body">
				<div class="advantages__text">Мы постоянно проводим акции и спецпредложения. Вы можете купить ПВХ окна недорого от производителя в Брянске и Брянской области и дополнительно получить приятный бонус.</div>
			</div>
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/montag.png" alt=""></div>
				<div class="advantages__title">Профессиональный монтаж <br>в любое время года</div>
			</div>
			<div class="advantages__body">
				<div class="advantages__text">Демонтаж и монтаж осуществят сертифицированные, штатные сотрудники, с солидным опытом работы.</div>
			</div>
		</div>
		<div class="advantages__item">
			<div class="advantages__head">
				<div class="advantages__img"><img src="/f/i/advantages/compleks.png" alt=""></div>
				<div class="advantages__title">Комплексный подход <br>к каждому клиенту</div>
			</div>
			<div class="advantages__body">
				<div class="advantages__text">Квалифицированный подход к решению задач любой сложности для оптимального выбора и быстрого решения любого вопроса.</div>
			</div>
		</div>
	</div>
</div>

app/views/site/_catalog.php
<?php
	use yii\helpers\Url;
?>

<section class="section">
	<div class="section__inner">
		<div class="container">
			<div class="section__title">каталог <span class="section__title_blue">продукции</span></div>
			<div class="section__text">В нашей компании вы можете купить окна из  ПВХ и алюминия уже сегодня! Мы располагаем собственным производством и предоставляем клиентам огромный ассортимент светопрозрачных конструкций из алюминиевого и ПВХ профилей. Всегда предложим вам лучшее решение, идеально подобранное под ваше помещение: частный дом, квартиру, офис, магазин или салон красоты. Познакомиться с ценами на пластиковые окна в Брянске вы можете непосредственно на этом официальном сайте.</div>

			<div class="catalog js__catalog-spoiler">
				<div class="catalog__list">
					<? foreach ($categoryList as $key => $category): ?>
						<a href="<?= Url::toRoute(['production/category', 'cat' => $category->slug]); ?>" class="catalog__item js__catalog-spoiler-item" style="background-image: url('<?= $category->image ?>');">
							<div class="catalog__body">
								<div class="catalog__icon">
									<img src="<?= $category->icon ?>" alt="">
								</div>
								<div class="catalog__title"><?= $category->title ?></div>
							</div>
						</a>
					<? endforeach; ?>
				</div>

				<div class="catalog__btn">
					<a href="#" class="btn js__catalog-spoiler-btn" data-open-text="Скрыть" data-hide-text="Показать еще" >Показать еще</a>
				</div>
			</div>

		</div>
	</div>
</section>

app/views/site/_clients-slider.php
<div class="clients-slider">
	<div class="clients-slider__inner">
		<div class="clients-slider__list">
			<div class="clients-slider__item"><img src="/f/i/clients/agroinvest-client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/instroy-client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/metr-client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/morf-client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/pishekombinat-bezhickiy-client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/bryanskselmash-client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/pochta-rossii-client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/ptibo-client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/rjd-client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/transneft--client-img.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/km.png" alt=""></div>
			<div class="clients-slider__item"><img src="/f/i/clients/vega.jpg" alt=""></div>
		</div>
	</div>
</div>

app/views/site/_feedback-slider.php
<div class="feedback-slider">
	<div class="feedback-slider__inner">
		<div class="feedback-slider__list">

			<? foreach ($reviews as $key => $review): ?>
				<div class="reviews__item">
					<div class="reviews__name"><?=$review->title;?></div>
					<div class="reviews__date"><?=$review->date;?></div>

						<div class="reviews__text">
							<?=$review->text;?>
						</div>

						<? if($review->image): ?>
							<div class="reviews__origin">
								<div class="reviews__origin-icon"><img src="/f/i/icon-review-origin.png" alt=""></div>
								<a href="<?=$review->image;?>" class="easyii-box">Посмотреть оригинал отзыва</a>
							</div>
						<? endif; ?>

				</div>
			<? endforeach; ?>

		</div>
		<div class="feedback-slider__btn">
			<a href="/about/reviews" class="btn">посмотреть все отзывы</a>
		</div>
	</div>
</div>

app/views/site/_top-slider.php
<section class="section">
	<div class="top-slider">
		<div class="top-slider__inner">
			<div class="top-slider__slider">

				<? foreach ($slides as $key => $slide): ?>
					<div
						class="top-slider__item"
						style="background-image: url('<?= $slide->image; ?>');"
					>
						<div class="container">
							<div class="top-slider__body">
								<? if ($slide->title): ?>
									<div class="top-slider__btn top-slider__btn_<?= $slide->model->btn_position; ?>">
										<a href="<?= $slide->link; ?>" class="btn"><?= $slide->title; ?></a>
									</div>
								<? endif; ?>
							</div>
						</div>
					</div>
				<? endforeach; ?>
			</div>
		</div>
	</div>

	<a href="<?= $slide->link; ?>" class="top-slider top-slider_phone">
		<div class="top-slider__inner">
			<div class="top-slider__slider">

				<? foreach ($slides as $key => $slide): ?>
					<div
						class="top-slider__item"
						style="background-image: url('<?= $slide->image; ?>');"
					>
						<div class="container">
							<div class="top-slider__body">

							</div>
						</div>
					</div>
				<? endforeach; ?>
			</div>
		</div>
	</a>
</section>

app/views/site/_works-slider.php
<?
	use yii\easyii\helpers\Image;

	$works = [
		'/f/i/works/information_items_258.png',
		'/f/i/works/information_items_288.jpg',
		'/f/i/works/information_items_430.jpg',
		'/f/i/works/information_items_497.jpg',
		'/f/i/works/information_items_528.png',
		'/f/i/works/information_items_539.jpg',
	];
?>

<div class="works-slider">
	<div class="works-slider__inner">
		<div class="works-slider__list">
			<?/* foreach ($works as $key => $work): ?>
			<div class="works-slider__item">
				<img src="<?= $work->image; ?>" alt="" class="works-slider__img">
			</div>
			<? endforeach; */?>

			<? foreach ($works as $key => $img): ?>
			<div class="works-slider__item">
				<img src="<?= Image::thumb($img, 880, 480, true); ?>" alt="" class="works-slider__img">
			</div>
			<? endforeach; ?>

		</div>
		<div class="works-slider__btn">
			<a href="/our-works/okna-pvh" class="btn">посмотреть все фотографии</a>
		</div>
	</div>
</div>

app/views/site/error.php
<?php
use yii\helpers\Html;
$this->title = $name;
?>

<div class="section">
	<div class="container">
		<div class="section__title"><?= Html::encode($this->title) ?></div>

		<div class="alert alert-danger">
			<?= nl2br(Html::encode($message)) ?>
		</div>

		<p>
			The above error occurred while the Web server was processing your request.
		</p>
		<p>
			Please contact us if you think this is a server error. Thank you.
		</p>

	</div>
</div>

app/views/site/index.php
<?php
	use app\modules\pages\api\Page;
	$this->title = $page->seo('title', $page->model->title);
	$this->registerMetaTag(
		['name' => 'description',
		'content' => $page->seo('description', $page->model->title)
	]);

	use yii\helpers\Url;
?>

	<?= $this->render('_top-slider', [
		'slides' => $slides
	]);?>

	<section class="section">
		<div class="container">
			<div class="section__title"><?= Page::title('популярные предложения окон'); ?></div>
			<div class="section__text">Мы предлагаем купить окна из  ПВХ и алюминия на выгодных условиях. Стоимость пластиковых окон формируется исходя из выбранного варианта стеклопакета, количества глухих и открывающихся створок, вида профиля, фурнитуры (оконные ручки, петли, ограничители, фиксаторы, замки). Точные расчеты по ценам производят специалисты  индивидуально для каждого клиента после выполнения замеров проемов.</div>
			<?= $this->render('_popular', []);?>
		</div>
	</section>

<div class="section__title">Пройдите тест <br> <span class="section__title_separate section__title_xsmall">и получите полный расчет <br> <span class="section__title_blue">стоимости своих окон, <br> скидку до 20% и подарок</span></span></div>
	
	<div class="marquiz__container marquiz__container_inline">
  <a class="marquiz__button marquiz__button_blicked marquiz__button_rounded marquiz__button_shadow" href="#popup:marquiz_5fc6239e710f3a0044ded0ed" data-fixed-side="" data-alpha-color="rgba(0, 168, 236, 0.5)" data-color="#00A8EC" data-text-color="#ffffff">Пройти тест</a>
</div>
	<br><br>
<!--	<section class="section section_get-measure">
		<div class="container">
			<div class="get-measure">
				<div class="get-measure__inner">
					<div class="get-measure__title">Оставьте заявку на замер</div>
					<div class="get-measure__body">
						<div class="get-measure__content">
							<div class="get-measure__main-img"><img src="/f/i/presents-stuff.png" alt=""></div>
							<div class="get-measure__present">
								<div class="get-measure__present-img"><img src="/f/i/icon-present.png" alt=""></div>
								<div class="get-measure__present-text">И получите комплект <br>по уходу за окнами <br>в подарок!</div>
							</div>
							<div class="get-measure__list">
								<div class="get-measure__list-header">Подарки:</div>
								<div class="get-measure__list-item">моющее средство для пвх окон</div>
								<div class="get-measure__list-item">средство для ухода за уплотнителем </div>
								<div class="get-measure__list-item">смазка для фурнитуры</div>
								<div class="get-measure__list-item">многоразовая салфетка “Микроспан”</div>
							</div>
						</div>
						<div class="get-measure__form-wrapper">
							<form action="" class="get-measure__form js__form">
								<div class="get-measure__input">
									<div class="input">
										<div class="input__wrapper">
											<input type="text" class="input__input" placeholder="Ваше имя" data-type="name" name="name">
										</div>
									</div>
								</div>
								<div class="get-measure__input">
									<div class="input">
										<div class="input__wrapper">
											<input type="text" class="input__input" placeholder="Ваш телефон" data-type="phone" name="phone">
										</div>
									</div>
								</div>
								<div class="get-measure__checkbox">
									<label class="checkbox">
										<input type="checkbox" class="checkbox__input" data-type="checkbox">
										<div class="checkbox__icon"></div>
										Я ознакомился и согласен с&nbsp;<span data-popup-open="agreement">правилами</span>
									</label>
								</div>
								<div class="get-measure__btn">
									<button class="btn">Оставьте заявку на замер</button>
								</div>
								<div class="response"></div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section> -->

	<?= $this->render('_catalog', [
		'categoryList' => $categoryList
	]);?>

	<section class="section section_gray section_about">
		<div class="section__inner">
			<div class="container">
				<div class="section__title">
					<?= Page::title('об окнах диса'); ?>
				</div>
				<div class="section__text">
					<p>В 2003 году новым участником рынка производства светопрозрачных конструкций стала компании «Окна ДИСА». Динамично развивающееся предприятие уже более 12 лет изготавливает металлопластиковые окна и двери ПВХ и изделия из алюминиевого профиля, используя традиционные для данных продуктов технологии и богатый профессиональный опыт.</p>
					<p>Собственные производственные мощности компании «Окна ДИСА» позволяют изготавливать широкое разнообразие светопрозрачных конструкций из профиля ПВХ и алюминия высочайшего качества, как типовые, так и эксклюзивные, технологически сложные изделия.</p>
				</div>
				<div class="section__link">
					<a href="/about/about-us">читать всю историю</a>
					
				</div>
			</div>
		</div>
	</section>
	<section class="section section_service-step">
		<div class="section__inner">
		<div class="container">
			<div class="section__title"><?= Page::title('пластиковые окна «ОТ И ДО»'); ?></div>
			<div class="section__subtitle">Возьмем на себя все ваши заботы по установке окон</div>
			<div class="section__text">
				<p>У нас вы можете не только заказать пластиковые или алюминиевые  окна в Брянске по выгодной цене, но и воспользоваться всеми<br> преимуществами профессионального сервиса. Выполнение замеров предоставляется бесплатно. Опытные мастера обеспечат <br>квалифицированное консультирование по любым вопросам, грамотный монтаж.</p>
			</div>
		</div>
		<div class="service-step">
			<div class="service-step__list">
				<? foreach ($services as $key => $service): ?>

					<? if ($key === 2): ?>
						<div class="service-step__item" style="background-image: url('/f/i/2-08325521f.jpg');">
							<div class="service-step__row">
								<div class="service-step__num">3</div>
								<div class="service-step__content">
									<div class="service-step__title">Заключение договора и&nbsp;оплата</div>
									<div class="service-step__btn">
										<a href="#" class="btn">варианты оплаты заказа</a>
									</div>
								</div>
							</div>
						</div>
						<? continue ?>
					<? endif; ?>

					<? if ($key < 6): ?>
						<? $img = $service->model->image_preview ? $service->model->image_preview : $service->image; ?>
						<div class="service-step__item" style="background-image: url('<?= $img; ?>');" >
							<div class="service-step__row">
								<div class="service-step__num"><?=$key + 1;?></div>
								<div class="service-step__content">
									<div class="service-step__title"><?=$service->title;?></div>
									<div class="service-step__btn">
										<? if ($service->slug === 'professional-consultation'): ?>
											<button class="btn" data-popup-open="metering">Заказать консультацию</button>
										<? elseif ($service->slug === 'free-froze'): ?>
											<button class="btn" data-popup-open="metering">Вызвать замерщика</button>
										<? else: ?>
											<a href="<?= Url::toRoute(['services/view', 'slug' => $service->slug]); ?>" class="btn">Подробнее</a>
										<? endif; ?>
									</div>
								</div>
							</div>
						</div>
					<? endif; ?>

				<? endforeach; ?>

			</div>
		</div>
		</div>
	</section>
	<section class="section">
		<div class="section__inner">
			<div class="container">
				<div class="section__title"><?= Page::title('как мы завоевываем доверие'); ?></div>
				<?= $this->render('_advantages', []);?>
			</div>
		</div>
	</section>
	<section class="section section_get-now">
		<div class="container">
			<div class="get-now">
				<div class="get-now__inner">
					<div class="get-now__left">
						<div class="get-now__window"><img src="/f/i/get-now-window.png" alt=""></div>
						<div class="get-now__payment">
							<div class="get-now__payment-title">Другие <br>способы <br>оплаты:</div>
							<div class="get-now__payment-list">
								<div class="get-now__payment-item">Наличный <br>расчёт</div>
								<div class="get-now__payment-item">Безналичный <br>расчёт</div>
								<div class="get-now__payment-item">Банковские <br>карты</div>
								<div class="get-now__payment-item">Оплата в кредит</div>
							</div>
						</div>
					</div>
					<div class="get-now__right">
						<div class="get-now__title">закажите сейчас, платите потом</div>
						<div class="get-now__text"><div class="get-now__text-icon"><img src="/f/i/icon-clock.png" alt=""></div> Оформите рассрочку без первоначального <br>взноса. Первый платеж через месяц!</div>
						<form action="" class="get-now__form-wrapper js__form">
							<div class="get-now__form-row">
								<div class="get-now__input">
									<div class="input">
										<div class="input__wrapper">
											<input type="text" class="input__input" placeholder="Ваше имя" data-type="name" name="name">
										</div>
									</div>
								</div>
								<div class="get-now__input">
									<div class="input">
										<div class="input__wrapper">
											<input type="text" class="input__input" placeholder="Ваш телефон" data-type="phone" name="phone">
										</div>
									</div>
								</div>
							</div>
							<div class="get-now__checkbox">
								<label class="checkbox">
									<input type="checkbox" class="checkbox__input" data-type="checkbox">
									<div class="checkbox__icon"></div>
									Я ознакомился и согласен с&nbsp;<span data-popup-open="agreement">правилами</span>
								</label>
							</div>
							<div class="get-now__btn">
								<button class="btn">Получить проект</button>
							</div>
							<div class="response"></div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="section">
		<div class="section__inner">
			<div class="container">
				<div class="section__title"><?= Page::title('примеры выполненных работ'); ?></div>
				<?= $this->render('_works-tabs', [
					'works' => $works,
					'categoryWorks' => $categoryWorks
				]);?>
			</div>
		</div>
	</section>
	<section class="section section_gray">
		<div class="section__inner">
			<div class="container">
				<div class="section__title"><?= Page::title('что говорят о нас клиенты'); ?></div>

				<?= $this->render('_feedback-slider', [
					'reviews' => $reviews,
				]);?>
			</div>
		</div>
	</section>
	<section class="section section_get-project">
		<div class="container">
			<div class="get-project">
				<div class="get-project__inner">
					<div class="get-project__body">
						<div class="get-project__content">
							<div class="get-project__title">бесплатно <br>создадим проект <br>для ваших окон</div>
							<div class="get-project__text">Менеджер по снятым замерам в специальной программе cоздает макет изделия со всеми характеристиками. Таким образом, вы получаете несколько вариантов, различных по цене  и комплектации.</div>
						</div>
						<div class="get-project__form-wrapper">
							<form action="" class="get-project__form js__form">
								<div class="get-project__input">
									<div class="input">
										<div class="input__wrapper">
											<input type="text" class="input__input" placeholder="Ваше имя" data-type="name" name="name">
										</div>
									</div>
								</div>
								<div class="get-project__input">
									<div class="input">
										<div class="input__wrapper">
											<input type="text" class="input__input" placeholder="Ваш телефон" data-type="phone" name="phone">
										</div>
									</div>
								</div>
								<div class="get-project__checkbox">
									<label class="checkbox">
										<input type="checkbox" class="checkbox__input" data-type="checkbox">
										<div class="checkbox__icon"></div>
										Я ознакомился и согласен с&nbsp;<span data-popup-open="agreement">правилами</span>
									</label>
								</div>
								<div class="get-project__btn">
									<button class="btn">Получить проект</button>
								</div>
								<div class="response"></div>
							</form>
						</div>
						<div class="get-project__ruler"><img src="/f/i/ruler.png" alt=""></div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="section">
		<div class="section__inner">
			<div class="container">
				<div class="section__title">наши <span class="section__title_blue">клиенты</span></div>
				<?= $this->render('_clients-slider', []);?>
			</div>
		</div>
	</section>
	<section class="section section_gray section_get-callback">
		<div class="section__inner">
			<div class="container">
				<div class="section__title"><?= Page::title('есть вопрос, на который <br>не нашли ответ'); ?></div>
				<div class="section__subtitle">Закажите звонок, и мы Вам перезвоним</div>
				<div class="get-callback">
					<div class="get-callback__inner">
						<form class="get-callback__form js__form">
							<div class="get-callback__input">
								<div class="input">
									<div class="input__wrapper">
										<input type="text" class="input__input" placeholder="Ваше имя" data-type="name" name="name">
									</div>
								</div>
							</div>
							<div class="get-callback__input">
								<div class="input">
									<div class="input__wrapper">
										<input type="text" class="input__input" placeholder="Ваш телефон" data-type="phone" name="phone">
									</div>
								</div>
							</div>
							<div class="get-callback__checkbox">
								<label class="checkbox">
									<input type="checkbox" class="checkbox__input" data-type="checkbox">
									<div class="checkbox__icon"></div>
									Я ознакомился и <br>согласен с&nbsp;<span data-popup-open="agreement">правилами</span>
								</label>
							</div>
							<div class="get-callback__btn">
								<button class="btn">Отправить</button>
							</div>
							<div class="response"></div>
						</form>
					</div>
					
				</div>
			</div>
		</div>
	</section>