app/modules/shops/models/Text.php
<?php
namespace app\modules\shops\models;

use Yii;
use yii\easyii\behaviors\CacheFlush;

class Text extends \yii\easyii\components\ActiveRecord
{
    const CACHE_KEY = 'easyii_text_shops';

    public static function tableName()
    {
        return 'app_shopss';
    }

    public function rules()
    {
        return [
            ['text_id', 'number', 'integerOnly' => true],
            [['text', 'address', 'city', 'district', 'coordinates', 'centermap', 'phone', 'worktime', 'manager'], 'trim'],
            ['slug', 'match', 'pattern' => self::$SLUG_PATTERN, 'message' => Yii::t('easyii', 'Slug can contain only 0-9, a-z and "-" characters (max: 128).')],
            ['slug', 'default', 'value' => null],
            ['slug', 'unique']
        ];
    }

    public function attributeLabels()
    {
        return [
            'text' => Yii::t('easyii/shops', 'Text'),
            'city' => 'Город',
            'district' => 'Район',
            'address' => Yii::t('easyii/shops', 'Address'),
            'coordinates' => Yii::t('easyii/shops', 'Coordinates'),
            'centermap' => Yii::t('easyii/shops', 'Centermap'),
            'phone' => Yii::t('easyii/shops', 'Phone'),
            'worktime' => Yii::t('easyii/shops', 'Worktime'),
            'manager' => Yii::t('easyii/shops', 'Manager'),
            'slug' => Yii::t('easyii/shops', 'Slug'),
        ];
    }

    public function behaviors()
    {
        return [
            CacheFlush::className()
        ];
    }
}

app/modules/shops/controllers/AController.php
<?php
namespace app\modules\shops\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\widgets\ActiveForm;

use yii\easyii\components\Controller;
use app\modules\shops\models\Text;

class AController extends Controller
{
    public $rootActions = ['create', 'delete'];

    public function actionIndex()
    {
        $data = new ActiveDataProvider([
            'query' => Text::find(),
        ]);
        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionCreate($slug = null)
    {
        $model = new Text;

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{
                if($model->save()){
                    $this->flash('success', Yii::t('easyii/shops', 'Text created'));
                    return $this->redirect(['/admin/'.$this->module->id]);
                }
                else{
                    $this->flash('error', Yii::t('easyii', 'Create error. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        }
        else {
            if($slug){
                $model->slug = $slug;
            }
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    public function actionEdit($id)
    {
        $model = Text::findOne($id);

        if($model === null){
            $this->flash('error', Yii::t('easyii', 'Not found'));
            return $this->redirect(['/admin/'.$this->module->id]);
        }

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{
                if($model->save()){
                    $this->flash('success', Yii::t('easyii/shops', 'Text updated'));
                }
                else{
                    $this->flash('error', Yii::t('easyii', 'Update error. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        }
        else {
            return $this->render('edit', [
                'model' => $model
            ]);
        }
    }

    public function actionDelete($id)
    {
        if(($model = Text::findOne($id))){
            $model->delete();
        } else {
            $this->error = Yii::t('easyii', 'Not found');
        }
        return $this->formatResponse(Yii::t('easyii/shops', 'Text deleted'));
    }
}

app/modules/shops/views/a/_form.php
<?php
    use yii\helpers\Html;
    use yii\helpers\Url;
    use yii\widgets\ActiveForm;
    use yii\easyii\widgets\Redactor;
?>
<?php $form = ActiveForm::begin([
    'enableAjaxValidation' => true,
    'options' => ['class' => 'model-form']
]); ?>


<div class="row">
	<div class="col-sm-6">
		<?= $form->field($model, 'city') ?>
	</div>
	<div class="col-sm-6">
		<?= $form->field($model, 'district') ?>
	</div>
	<div class="col-sm-12">
		<?= $form->field($model, 'address') ?>
	</div>
	<div class="col-sm-6">
		<?= $form->field($model, 'coordinates') ?>
	</div>
	<div class="col-sm-6">
		<?= $form->field($model, 'centermap') ?>
	</div>
</div>

<hr>

<div class="row">
	<div class="col-sm-6">
		<?= $form->field($model, 'manager')->widget(Redactor::className(),[
		    'options' => [
		        'minHeight' => 100,
		        'imageUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'services']),
		        'fileUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'services']),
		        'plugins' => ['fullscreen']
		    ]
		]) ?>
	</div>
	<div class="col-sm-6">
		<?= $form->field($model, 'phone')->widget(Redactor::className(),[
		    'options' => [
		        'minHeight' => 100,
		        'imageUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'services']),
		        'fileUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'services']),
		        'plugins' => ['fullscreen']
		    ]
		]) ?>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<?= $form->field($model, 'worktime')->widget(Redactor::className(),[
		    'options' => [
		        'minHeight' => 200,
		        'imageUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'services']),
		        'fileUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'services']),
		        'plugins' => ['fullscreen']
		    ]
		]) ?>
	</div>
	
</div>

<?//= (IS_ROOT) ? $form->field($model, 'slug') : '' ?>
<?= Html::submitButton(Yii::t('easyii', 'Save'), ['class' => 'btn btn-primary']) ?>
<?php ActiveForm::end(); ?>

app/modules/shops/views/a/_menu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>
<?php if(IS_ROOT) : ?>
    <ul class="nav nav-pills">
        <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
            <a href="<?= $this->context->getReturnUrl(['/admin/'.$module]) ?>">
                <?php if($action === 'edit') : ?>
                    <i class="glyphicon glyphicon-chevron-left font-12"></i>
                <?php endif; ?>
                <?= Yii::t('easyii', 'List') ?>
            </a>
        </li>
        <li <?= ($action === 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/create']) ?>"><?= Yii::t('easyii', 'Create') ?></a></li>
    </ul>
    <br/>
<?php elseif($action === 'edit') : ?>
    <ul class="nav nav-pills">
        <li>
            <a href="<?= $this->context->getReturnUrl(['/admin/'.$module])?>">
                <i class="glyphicon glyphicon-chevron-left font-12"></i>
                <?= Yii::t('easyii/shops', 'Texts') ?>
            </a>
        </li>
    </ul>
    <br/>
<?php endif; ?>

app/modules/shops/views/a/create.php
<?php
$this->title = Yii::t('easyii/shops', 'Create text');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

app/modules/shops/views/a/edit.php
<?php
$this->title = Yii::t('easyii/shops', 'Edit text');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

app/modules/shops/views/a/index.php
<?php
use yii\helpers\Url;

$this->title = Yii::t('easyii/shops', 'Texts');

$module = $this->context->module->id;
?>

<?= $this->render('_menu') ?>

<?php if($data->count > 0) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <th><?= Yii::t('easyii/shops', 'Address') ?></th>
                <th width="30"></th>
            </tr>
        </thead>
        <tbody>
    <?php foreach($data->models as $item) : ?>
            <tr>
                <td><a href="<?= Url::to(['/admin/'.$module.'/a/edit', 'id' => $item->primaryKey]) ?>"><?= $item->address ?></a></td>
                <td><a href="<?= Url::to(['/admin/'.$module.'/a/delete', 'id' => $item->primaryKey]) ?>" class="glyphicon glyphicon-remove confirm-delete" title="<?= Yii::t('easyii', 'Delete item') ?>"></a></td>
            </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
    <?= yii\widgets\LinkPager::widget([
        'pagination' => $data->pagination
    ]) ?>
<?php else : ?>
    <p><?= Yii::t('easyii', 'No records found') ?></p>
<?php endif; ?>